### ISSUE TITLE
Dragging between lists? Nested lists? Wanna build a sortable tree

### ISSUE THREAD

**Issue by lolmaus** [kalcifer/ember-dragula#17]
Here's a prototype I built long ago with jQuery UI Sortable: http://hivemindunit.github.io/hivemind-frontend-prototype/settings/domains/categories2/

I'm now trying to do an identical tree with Ember, and turns out to be a tough nut to crack due to the lack of high-level drag-n-drop abstractions. :(

Is `ember-dragula` able to power a sortable tree like that?

**Comment by pksjce** [comment]
So, I wrote this plugin because I had to build a reorder feature for my lists. 
If you start the `ember server` on this project. You will see an example list which can be reordered by dragging and dropping items.

I also tried to apply this library for a mac finder kind of view where one can drop files into folders and reorder in the same UI. This turned out to be too hard and then I switched to [http://interactjs.io/](http://interactjs.io/) which had better event hooks. Though, for single list reordering dragula library works very well with sophisticated animations out of the box.
